version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: node:12
jobs:
  setup:
    executor:
      name: default
    steps:
      - run:
          name: Install dependencies
          command: npm install
  test:
    executor:
      name: default
    steps:
      - run:
          name: Test
          command: echo "hello"