version: 2
jobs:
  build:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: echo "hello"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test